name: Build and deploy Node.js app to Azure Web App - video-sharing-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or your required Node.js version

    # Step 3: Install dependencies and build
    - name: Install dependencies and build
      run: |
        cd backend
        npm install
        npm run build --if-present

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'video-sharing-app2'
        slot-name: 'Production'
        package: ./backend
        publish-profile: ${{ secrets.VIDEOSHARINGAPPTWOSECRETS }}